baseURL = 'https://zhouyujt.github.io/wge/'
title = 'WGE'
theme = 'hugo-theme-relearn'
defaultContentLanguage = 'en'

[languages]
   [languages.zh]
    contentDir = 'content/zh'
    languageCode = 'zh-CN'
    languageName = '简体中文'
    title = 'WGE'
    weight = 1

  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en'
    languageName = 'English'
    title = 'WGE'
    weight = 2

[params]
  disableLandingPageButton = true
  themeVariant = 'blue'
  disableRootBreadcrumb = true

  
